matrix:
  include:
    - language: perl
      perl: 5.30
      install: ""
      script: ./test_parser.sh perl parser_perl.pl

    - language: python
      python: 3.8
      script: ./test_parser.sh python parser_python.py

    - language: ruby
      script: ./test_parser.sh ruby parser_ruby.rb


    - language: node_js
      node_js: "8"
      script: ./test_parser.sh node parser_javascript.js

    - language: go
      install: go build parser_go.go
      script: ./test_parser.sh ./parser_go


    # nim
    - language: minimal
 	    dist: bionic
      install:
        - sudo apt-get -y install nim
      script:
        - nim c -d:release parser_nim.nim
        - ./test_parser.sh ./parser_nim
